version: '3.8'

services:
  webscraper:
    image: pinchapapas/webscraper:latest
    environment:
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - MY_WHATSAPP_NUMBER=${MY_WHATSAPP_NUMBER}
      - URL=${URL}
    restart: always
    volumes:
      - .:/app
    command: ["python", "/app/webscraper.py"]